### ISSUE TITLE
What do I do with nginx proxy manager?

### ISSUE THREAD

**Issue by anonymous-99529** [timelordx/synology-cert-deploy#1]
nginx proxy manager has a numbering that increases the number every time I renew the cert, ex) privkey1.pem, privkey2.pem... In this case, how should I specify the location?

**Comment by timelordx** [comment]
I wrote a helper script for such situations. The script detects where the latest key/cert is located and provides that as an input for [synology-cert-deploy.sh](https://github.com/timelordx/synology-cert-deploy/blob/main/synology-cert-deploy.sh) in form of environment variables. I'll try to upload it here tomorrow. Hopefully it'll help.

But if you'd like to meantime write your own helper script, all you need to do is to run the following before running `synology-cert-deploy.sh`:

```
export SYNO_HELPER_KEY="/path/to/your/privkey.pem"
export SYNO_HELPER_FULLCHAIN="/path/to/your/fullchain.pem"
```

If your helper script can populate those two environment variables, the `synology-cert-deploy.sh` script will take it from there. Just run your helper script right before you run `synology-cert-deploy.sh`.

**Comment by timelordx** [comment]
As promised, I've uploaded the helper script example - [synology-helper-example.sh](https://github.com/timelordx/synology-cert-deploy/blob/main/synology-helper-example.sh). The only purpose of the helper script is to find where the most recent key and certificate chain files are located and set the environment variables for `synology-cert-deploy.sh` to use. You can edit it to match your requirements. The script contains a usage example as well.

In your case, you will need to edit the helper script as follows:

```
search_filter='privkey*.pem'
search_location='/path/to/your/certificate/directory'
```
I would suggest setting the `search_filter` based on the certificate file name rather than the key file name.

Also, you will need to edit this, which is the most important part (you can pretty much throw away most of my example code except this part):

```
export SYNO_HELPER_KEY="${search_result_dir}/privkey.pem"
export SYNO_HELPER_FULLCHAIN="${search_result_dir}/fullchain.pem"
```
and replace `privkey.pem` and `fullchain.pem` with whatever your files are. You can add your own code to the helper script to help you find those file names. It should be easy. For example (I'm guessing here, because I am not familiar with the folder structure of Nginx Proxy Manager):

```
export SYNO_HELPER_KEY="$( ls -1tr /path/to/your/certificate/directory/privkey*.pem | tail -1 )"
export SYNO_HELPER_FULLCHAIN="$( ls -1tr /path/to/your/certificate/directory/chain*.pem | tail -1 )"
```

Then, as root, run the helper script first followed by `synology-cert-deploy.sh`:
```
source ./synology-helper-example.sh
./synology-cert-deploy.sh
```

Or as sudo:
```
sudo bash -c 'source ./synology-helper-example.sh; ./synology-cert-deploy.sh'
```

You could even simplify everything down to just the following and completely throw away my entire helper script:

```
export SYNO_HELPER_KEY="$( ls -1tr /path/to/your/certificate/directory/privkey*.pem | tail -1 )"
export SYNO_HELPER_FULLCHAIN="$( ls -1tr /path/to/your/certificate/directory/chain*.pem | tail -1 )"
./synology-cert-deploy.sh
```
But I'm oversimplifying right now, because as I said, I am not familiar with the folder structure of Nginx Proxy Manager.

In any case, my helper script example is really just a template to help you going. I use it with my Caddy Web Server, which can use multiple certificate providers and have keys/chains in multiple directories. The helper script helps me find the latest one, so that `synology-cert-deploy.sh` can then use it.

**Comment by anonymous-99529** [comment]
Thank you for your very useful script, and for your detailed and kind reply! I'll try it over the weekend.

**Comment by anonymous-99529** [comment]
I just tried it as you taught me and it worked perfectly, thank you so much!

**Comment by timelordx** [comment]
Excellent! Thank you for reporting back the result!
